import express from "express";
import authRoutes from "./routes/auth";
import taskRoutes from "./routes/task";
import userRoutes from "./routes/user";
import { track } from "./middlewares/track";
import credentials from "./middlewares/credentials";
import corsOptions from "./config/cors";
import cors from "cors";
import cookieParser from "cookie-parser";
const app = express();
app.use(cookieParser());
app.use(credentials);
app.use(cors(corsOptions));
app.use(express.json());
app.use("/", track);
app.use("/auth", authRoutes);
app.use("/tasks", taskRoutes);
app.use("/user", userRoutes);

export default app;
